language: java
matrix:
  include:
    - jdk: oraclejdk8
script: travis_retry ./gradlew clean headless allTests coverage coveralls -i
before_install:
          - "export DISPLAY=:99.0"
          - "sh -e /etc/init.d/xvfb start"

notifications:
  slack: cs2103:IB11twnpehzmqfmHoqNBvkBD

addons:
  apt:
    packages:
      - oracle-java8-installer
